language: go
go:
- 1.12.x
env:
  global:
  - secure: K9WAEtoTj944dQasWTi3ixNiebK0wiVqh/OldI37g4w+tddSoTvSvTq8+Dz5vUpAzDHwRrgx+EHCUOpGpntNlnEqf9GxDW9DHf8RM4l4CQVA2XqwdaonvlrZ6O0MFBriTLr0d59RSb0WdY+Gt/GmBAzuB7Q1YZmV7BS89jnzGNOzLUBAUw1RFKis0craChNOfHMy38rHFmLIphda6tmh6GqKsUo18b3yfqKhYVoIIgADtB6jLw2KGTNN7kj8bDv2DT4GCmr0oUZOE8JJh0IvizHYBK5f+PYl8vEtNiWlvR7wdfnmKKx8+KTsM55pX8puVm3X+TFE5jG8McexTmZxaEZjxcDYl0EczS5bX6LsyQuJ41x1iv0H2UwOtEKHzzft2FxTSShzxbCQUhFqZgo6Y77BaG87txtqVIaR/1XuHJeY82v/A9a8kBW6/6jKMFnCfHVRfIOeQZi8jiLgtBGLGnILiq6yDP0NGupPVSkvl/9mmlp2wlbz+BcUncAuYXM9sj2fK5DO+h+BzOFvl9iTw21mqhknCVGN/zUJS5XlqKAULVB3RNDR5fT9dUufy50bxC5YfsExSlW3vQWZz7DJIYpaud4j7M0LMwAG/x9tatZ32NV9TWDZ+/pY4eYk5VYytfhLiI0iFPKbHwzsYeRA851PoesHDhPdLN8ujeZPgXo= #DOCKER_USER
  - secure: CsLKK6fKbFsgTRvBhBb2nEV8D5PjTII/JZY6enSmLDMRQkObQ+v7hyniD1K83c8nFbPJ7oXl1nwYttmvZhkj3YOzdxYa8Cyhyne17LHZas1NA5Y/QukZpIIcQvVf+A2fcztdgutFrQO4PIjn2P5Ear82k+y4fdeBHTwQuai8j6Az2QDPSH4Nygw+heqNsPJspi2qyR2HAtTQ1piS7uVhtINLBY8w/FoHJqgmcpR3dEYir0gQ5GGeMIadLRKFV+wTLRsK/+tfopBZHtLb5OeVq3/8eg/4SM4NoXhb9NPiVk8d4b6DULQ15dGdAVQT5Bg12dsWAxPZHLYgPg/o9lUVZTuOfwBHm9Bf8Lu8A/ECjRM93MYR+/lKeBm2zLUJn07STCuOirNSTzo4XeNe2LIh0YeZeEKeeRZzSTt0TZzXLRVg16kVYF4f1ZvjIhoRQWBmB69bF8rzE3ZrzDZ+95MfyoEwDQF3aBrQxrfMYmshBrsNYOyxtuXthuRuHzieSVnbePyYus8qUnZYOai5BvNrMUX4DaxbLHte4pV0VcfEZ3QcOtbQfAQeVC+CzdgIA+OMHa9QiEOYEfBjNhapZx4aaOwR6OTciI/GJ8ydxZEVrs4w4rJ5sc8zdTPcKNYl0AgurhdVh7uSour16c/wY6iJJKrN7YTG9JcO2rka+p3o3XI= #DOCKER_PASS
sudo: required
services:
- docker
script:
- sudo apt update && sudo apt install libzmq3-dev
- docker pull navitia/mock-kraken:dev
- make setup
- make linter-install
- make ci
- make
after_success:
- export REPO=navitia/schedules
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- make docker
- docker tag $REPO:$(make version) $REPO:$TAG
- docker tag $REPO:$(make version) $REPO:travis-$TRAVIS_BUILD_NUMBER
- if [ -n "$DOCKER_USER" ] && [ -n "$DOCKER_PASS" ]; then docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push $REPO; fi
