language: go
go:
    - "1.10.x"
    - master
sudo: required
services:
    - docker
script:
    - sudo apt install libzmq3-dev
    - make setup
    - make ci
    - make
matrix:
  allow_failures:
    - go: master
