name: Create and publish master image

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  CreateAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install zip dependency
        run: |
          sudo apt-get update
          sudo apt install -y httpie

      - name: Install libzmq3
        run: sudo apt install libzmq3-dev

      - name: Build a version
        run: make build

      - name: Build a Gormungandr image
        run: make docker

      - name: Login Docker hub
        run: make dockerhub-login DOCKERHUB_USER=${{secrets.DOCKERHUB_USER}} DOCKERHUB_PWD=${{secrets.DOCKERHUB_PWD}}

      - name: Push image gormungandr master
        run: make push-image-gormungandr-master

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          echo '{"text":":warning: Gormungandr Github Actions: Create image for branch master failed ! (https://github.com/CanalTP/gormungandr/actions/workflows/master.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}
