name: Create and publish release image

on:
  push:
    tags:
      - '*'

jobs:
  CreateAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install httpie dependency
        run: |
          sudo apt-get update
          sudo apt install -y httpie

      - name: Install libzmq3
        run: sudo apt install -y libzmq3-dev

      - name: Build a version
        run: make build

      - name: Build a Gormungandr image
        run: make docker

      - name: Login Docker hub
        run: make dockerhub-login DOCKERHUB_USER=${{secrets.DOCKERHUB_USER}} DOCKERHUB_PWD=${{secrets.DOCKERHUB_PWD}}

      - name: Push image gormungandr release
        run: make push-image-gormungandr-release

      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          echo '{"text":":warning: Gormungandr Github Actions: Create image for branch realse failed ! (https://github.com/CanalTP/gormungandr/actions/workflows/release.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}
      - name: trig publishing + notifications (the job has successed)
        if: success()
        run: |
          VERSION=$(make version)
          echo '{"text":":information_source: Gormungandr Github Actions: Create image for branch realse succeded - New image gormungandr' $VERSION 'is available"}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}